name: Sanitizer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  sanitizer:
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-11, clang++-13]
        sanitizer: [address, undefined]

    runs-on: ubuntu-22.04

    env:
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v3

      - run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}  -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }}"

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
